# -*- coding: utf-8 -*-
"""پیشبینی_اعتبار_وام.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7mQ9w2nQY1kI2oR7T9JEX6mKCVvddAx
"""

import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

data=pd.read_csv('loan.csv')

data.head()

data.drop(['Loan_ID'],axis=1,inplace=True)

data.dtypes

data.dtypes == 'object'

obj = (data.dtypes == 'object')
object_cols = list(obj[obj].index)
plt.figure(figsize=(18,36))
index = 1

for col in object_cols:
  y = data[col].value_counts()
  plt.subplot(11,4,index)
  plt.xticks(rotation=90)
  sns.barplot(x=list(y.index), y=y)
  index +=1

from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])
data['Married'] = label_encoder.fit_transform(data['Married'])
data['Education'] = label_encoder.fit_transform(data['Education'])
data['Self_Employed'] = label_encoder.fit_transform(data['Self_Employed'])
data['Property_Area'] = label_encoder.fit_transform(data['Property_Area'])
data['Loan_Status'] = label_encoder.fit_transform(data['Loan_Status'])

data['Gender']

data.head()

plt.close()
plt.figure(figsize=(11,8))
sns.heatmap(data.corr(), annot=True)
plt.show()

sns.catplot(x="Gender", y="Married",
            hue="Loan_Status",
            kind="bar",
            data=data)

data.isna().sum()

data['Dependents'].mean()

for col in data.columns:
  data[col] = data[col].fillna(data[col].mean())

data.isna().sum()

from sklearn.model_selection import train_test_split

X = data.drop(['Loan_Status'],axis=1)
Y = data['Loan_Status']
X.shape,Y.shape

X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.2,
                                                    random_state=42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.max_iter=10000
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

from sklearn import metrics



print(metrics.accuracy_score(Y_test,Y_pred)*100 , "%")